<?php

namespace AppBundle\Repository;

/**
 * TyrePalletRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TyrePalletRepository extends \Doctrine\ORM\EntityRepository
{
}
